# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180629_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('REP', '培训机构'), ('personal', '个人'), ('highuniversities', '高校')], default='REP', max_length=100, verbose_name='机构类别'),
        ),
    ]
