# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('rep', '培训机构'), ('personal', '个人'), ('highuniversities', '高校')], default='REP', max_length=100, verbose_name='机构类别'),
        ),
    ]
