# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=1, verbose_name='视频长度'),
        ),
    ]
