# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180628_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证类型'),
        ),
    ]
